export default {
  title: "Grubs",
  description: "Segmented squirming grub prototype",
  params: [
    {
      key: "speed",
      title: "Speed",
      defaultValue: 1,
      sliderMin: 0,
      sliderMax: 5,
    },
    {
      key: "spacing",
      title: "Spacing",
      defaultValue: 0.01,
      sliderMin: 0,
      sliderMax: 0.1,
    },
    {
      key: "baseScale",
      title: "Base Scale",
      defaultValue: 0.6,
      sliderMin: 0.1,
      sliderMax: 2,
    },
    {
      key: "groupScale",
      title: "Group Scale",
      defaultValue: 1,
      sliderMin: 0.1,
      sliderMax: 5,
    },
    {
      key: "tailTaper",
      title: "Tail Taper",
      defaultValue: 0.45,
      sliderMin: 0,
      sliderMax: 1,
    },
    {
      key: "headTaper",
      title: "Head Taper",
      defaultValue: 0,
      sliderMin: 0,
      sliderMax: 1,
    },
    {
      key: "pulseAmp",
      title: "Pulse Amp",
      defaultValue: 0.28,
      sliderMin: 0,
      sliderMax: 1,
    },
    {
      key: "pulseFreq",
      title: "Pulse Freq",
      defaultValue: 4,
      sliderMin: 0,
      sliderMax: 15,
    },
    {
      key: "pulseTravel",
      title: "Pulse Travel",
      defaultValue: 0.8,
      sliderMin: 0,
      sliderMax: 3,
    },
    {
      key: "squirmAmpY",
      title: "Squirm Amp Y",
      defaultValue: 0.5,
      sliderMin: 0,
      sliderMax: 2,
    },
    {
      key: "squirmFreq",
      title: "Squirm Freq",
      defaultValue: 3,
      sliderMin: 0,
      sliderMax: 12,
    },
    {
      key: "xWrapLimit",
      title: "X Wrap Limit",
      defaultValue: 20,
      sliderMin: 1,
      sliderMax: 100,
    },
  ],
};
